version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gorm_db
    #ports:
     # - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
     - "6379:6379"

  app:
    ports:
      - "8081:8080" 
    build: .
    command: go run main.go
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gorm_db
      DB_PORT: 5432

volumes:
  pgdata:
